### ISSUE TITLE
Intent to package: Snaps are universal Linux packages

### ISSUE THREAD

**Issue by brlin-tw** [nesv/uhttpd#1]
Dear maintainer(s), 

[Snaps are universal Linux packages](https://snapcraft.io) that can be installed and run on many GNU+Linux distributions with ease.  I've been following the [Snapcrafters](https://forum.snapcraft.io/t/join-snapcrafters/1325) instructions and [have built a working snap on the Snap Store](https://snapcraft.io/uhttpd), you may try it by running the following commands after [installing snapd](https://docs.snapcraft.io/installing-snapd/6735):
 
    sudo snap install --channel=edge --devmode uhttpd
    sudo sh -c "printf '<h1>Hello uhttpd snap</h1>' > /var/snap/uhttpd/common/index.html"
    xdg-open http://localhost:80

I'm also looking forward to working with you to make the packaging work upstream (if you're interested).  You may want to check out the current [packaging recipe](https://github.com/Lin-Buo-Ren/uhttpd-snap/blob/master/snap/snapcraft.yaml), the [documentation](https://docs.snapcraft.io), registering a developer account on the [Snap Store](https://snapcraft.io/store), and [get in touch with us](https://forum.snapcraft.io) to transfer the work under your control.

Thanks for your time and attention.

**Comment by nesv** [comment]
Thank you, @Lin-Buo-Ren. I've merged your pull request in.

**Comment by brlin-tw** [comment]
Great!  I would like to ask if you are interested in taking over the maintenance of the [uhttpd snap on the Snap Store](https://snapcraft.io/uhttpd) so that you can gain total control of this distribution?  I've just added your public e-mail address to the snap collaborator list so that you can manage the store metadata, releases (if there's any in the future), and other details of the snap.  If you're willing to take over the entire thing, here's the process:

1. Acquire a developer account on the Snap Store (essentially an Ubuntu One SSO account) and optionally, a [Snapcraft Forum](https://forum.snapcraft.io) account.
2. [Post a snap name transfer request under the `store-requests` topic category of the Snapcraft Forum](https://forum.snapcraft.io/search?q=transfer%20category%3Astore-requests), you'll have to mention either your snap account id listed in <https://dashboard.snapcraft.io/dev/account/> or the associated e-mail address.  You may check out this example: [Transfer brook - store - snapcraft.io](https://forum.snapcraft.io/t/transfer-brook/4966)
  I can also make the post for you, in this case simply mention the aforementioned account details here.
3. After the name transfer is completed, you may start using the [snapcraft build service](https://snapcraft.io/build) to set up the automatic snap build and publishing from this repository, you may manage the snap's release details at [the snap's releases page](https://snapcraft.io/uhttpd/releases)

It's also fine if you don't want to take over, in this case I'll setup a repo on Launchpad that will periodically sync this repository and build the snap.

Also, just if you're wondering, this project is featured in the [Snapcraft Live - 17th April 2019 - YouTube](https://www.youtube.com/watch?v=y0vtk5MDqA4) broadcast.

**Comment by nesv** [comment]
Thanks! I will send a name transfer request. 

EDIT: Nifty! I didn't realize this silly, little project had been featured on a broadcast! :laughing:
