### ISSUE TITLE
uhttpd for OpenWrt

### ISSUE THREAD

**Issue by stokito** [nesv/uhttpd#3]
Hi, just want to tell you that there is already a popular http server with the same name: uhttp for OpenWrt Linux which is used for routers:

https://openwrt.org/docs/guide-user/services/webserver/uhttpd

Just to avoid collision it may be good to rename your project

**Comment by nesv** [comment]
Thank you. I'm already aware of the OpenWRT uhttpd, but I wasn't at the time I wrote this dinky, little repo. I'm not terribly concerned about name collisions, but thank you all the same.

**Comment by megapro17** [comment]
You didn't wrote that your app is complete different software, it's not obvious

**Comment by nesv** [comment]
@megapro17 I actually did. From the README:

> If you are looking for the uhttpd that ships with OpenWRT, you are in the wrong place.
